const data = {
    de: {
      pairs: [
        ["tell", "vertellen"],
        ["air", "lucht"],
        ["also", "ook"],
        ["home", "thuis"],
        ["large", "grote"],
        ["must", "moet"],
        ["such", "dergelijke"],
        ["follow", "volgen"],
        ["men", "mannen"],
        ["light", "licht"],
        ["mother", "moeder"],
        ["new", "nieuwe"],
        ["place", "plaats"],
        ["after", "na"],
        ["only", "alleen"],
        ["boy", "jongen"],
        ["same", "hetzelfde"],
        ["about", "over"],
        ["many", "veel"],
        ["day", "day"],
      ],
      langA: { code: "en", name: "English" },
      langB: { code: "de", name: "Dutch" },
    },
    fr: {
      pairs: [
        ["a car", "une voiture"],
        ["the glass", "le verre"],
        ["the station", "la gare"],
        ["snow", "neige"],
        ["egg", "œuf"],
        ["goodbye", "au revoir"],
        ["spain", "l'espagne"],
        ["left", "gauche"],
        ["night", "nuit"],
        ["life", "vie"],
        ["horse", "cheval"],
        ["wood", "bois"],
        ["next", "suivant"],
        ["paper", "papier"],
        ["feet", "pieds"],
        ["girl", "fille"],
        ["soon", "bientôt"],
        ["song", "chanson"],
        ["door", "porte"],
        ["island", "île"]
      ],
      langA: { code: "en", name: "English" },
      langB: { code: "fr", name: "French" },
    },
  };
  
  export default data;